### PR TITLE
Evict unavailable elements and improve element compare performance

### PR DESCRIPTION
**Pull request by aristotelos**
Evict unavailable elements to prevent COM exceptions and to free memory. See https://github.com/FlaUI/FlaUI.WebDriver/issues/35. The COM exceptions from a growing set of unavailable elements may be the cause of degrading performance as well.

### CODE REVIEW

**Review by ddeltasolutions — APPROVED** [review]

**Comment by grokys** [comment]
I'm testing this with the hacky repro at https://github.com/grokys/FlaUI.WebDriver/tree/tests/slowdown-demo and it doesn't seem to help much. I'm seeing the `KnownElementsByElementReference` collection growing steadily even though the windows containing the elements have been closed, so looks like elements aren't getting evicted properly.

**Comment by grokys** [comment]
Looks like the [`ProcessId`](https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/AutomationElement.cs#L93) property is returning a value even when the window containing the element is no longer available, so `IsAvailable` is returning `true`.

**Comment by aristotelos** [comment]
> I'm testing this with the hacky repro at https://github.com/grokys/FlaUI.WebDriver/tree/tests/slowdown-demo and it doesn't seem to help much. I'm seeing the `KnownElementsByElementReference` collection growing steadily even though the windows containing the elements have been closed, so looks like elements aren't getting evicted properly.

I've done a quick performance profile and pushed an update that uses the RuntimeId for a fast initial comparison. I have tested with your manual performance test scenario and it seems to work!

**Review by ddeltasolutions — APPROVED** [review]

**Comment by grokys** [comment]
Thanks! This does seem to improve things, but also causes #42 :(

**Comment by grokys** [comment]
To give a bit more details on how much this helped:

The [Avalonia integration test suite](https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.IntegrationTests.Appium) before this PR took over an hour to run. After this PR, it takes less than 4 minutes ;)

**Comment by ddeltasolutions** [comment]
Great job!
Thank you

**Pull request merged**
